# GitHub Pages Configuration for Devin Wiki

# Site settings
title: "Devin AI Wiki for DevOps"
description: "Comprehensive documentation for using Devin AI with DevOps workflows, Infrastructure as Code, and OpenStack automation"
baseurl: "/devin-ai-wiki"
url: "https://agnosticdba.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Kramdown settings (GitHub Pages compatible)
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo

# Plugins (GitHub Pages compatible only)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - terraform/
  - ansible/
  - scripts/
  - .terraform/
  - "*.tfvars"
  - "*.tfstate"

# Site metadata
author:
  name: "AgnosticDBA"
  email: "peter@agnosticdba.com"

# Social links
github_username: AgnosticDBA
repository: "AgnosticDBA/devin-ai-wiki"

# Footer
footer_content: "This documentation is maintained as part of the AgnosticDBA DevOps learning resources."
